### ISSUE TITLE
Make inning arrow smaller to allow room for extras

### ISSUE THREAD

**Issue by ajbowler** [ajbowler/mlb-led-scoreboard#1]
Currently if it goes to the 10th inning the number runs out of room.

**Comment by swemoney** [comment]
I took a different spin on this and just moved the arrow to align to the top and then slide everything to the left when extras hits. #24

**Comment by ajbowler** [comment]
Closed by https://github.com/ajbowler/mlb-led-scoreboard/commit/eca1cc2029a30451768d71c6c3ce93c268c8f5d3
