### ISSUE TITLE
Fix submodules link

### ISSUE THREAD

**Issue by cschulerwiin** [ajbowler/mlb-led-scoreboard#5]
you may want to look at the matrix folder, it throws a 404 right now.

**Comment by ajbowler** [comment]
It appears to be tagged with a nonexistent commit that I made locally - I updated the config in their Makefile per my README to use my Adafruit hat.

I'll update the README to point to the other open source projects I use.

**Comment by ajbowler** [comment]
Fixed with https://github.com/ajbowler/mlb-led-scoreboard/commit/bbbb48e9190e29296cb26c9b1250e61fa3018d9a
