### ISSUE TITLE
Update Install Instructions in README

### ISSUE THREAD

**Issue by xjmsp** [ajbowler/mlb-led-scoreboard#58]
Wrote up some detailed instructions, from fresh image to finished, to get people going.  Use them if you'd like. (not really an issue, just didn't know how else to submit it)

----
## **Install MLB LED Scoreboard**
**Distribution: Raspbian Lite**

Enable SSH: Place a file named 'ssh', without any extension, onto the boot partition of the SD card

Connect to raspberry Pi with Putty via SSH
```
Default user: pi / raspberry
```
#change password: ```passwd```

**Disable snd_bcm2835** (see: https://github.com/hzeller/rpi-rgb-led-matrix#bad-interaction-with-sound)
```
cd /etc/modprobe.d
sudo nano alsa-blacklist.conf 
```
Type: ```blacklist snd_bcm2835```
Save: CTRL-O
Hit: enter to overwrite the existing file
Exit nano: CTRL-X

Restart: ```sudo reboot```

**Install Dependencies For The LED Matrix**
```
sudo apt-get install python-pip
sudo apt-get install libxml2-dev libxslt-dev
```

**Install Git Command**
```
sudo apt-get install git
```

**Git MLB LED Scoreboard**
```
git clone --recursive https://github.com/ajbowler/mlb-led-scoreboard
cd mlb-led-scoreboard/matrix/bindings/python
```

**Building the RGBMatrix binaries (what controls the LED board)**
```
sudo apt-get update && sudo apt-get install python2.7-dev python-pillow -y
sudo HARDWARE_DESC=adafruit-hat make build-python #If using the Adafruit hat with the flicker mod: adafruit-hat-pwm
sudo HARDWARE_DESC=adafruit-hat make install-python #If using the Adafruit hat with the flicker mod: adafruit-hat-pwm
```

**Demo (Scrolling text: Hello world!)**
```
cd samples
sudo ./runtext.py
```

**Finish up with MLB LED Scoreboard install**
```
cd ../.. #should be in bindings folder now
sudo pip install -e python/
cd ../../ #should be in mlb-led-scoreboard/ now
sudo pip install mlbgame #takes awhile
make
```

**Let's Run It!**
```
sudo python main.py #To stop the script: CTRL-C
```
**To Edit settings**
```
sudo nano config.json.example
```

**Edit the file to how you see fit**
Save: CTRL-O
Delete: .example
Confirm: New file
Exit: CTRL-X
#Now when you run 'sudo python main.py' it will display the team, standings, and anything else you have configured

//Thanks to:
//https://github.com/ajbowler/mlb-led-scoreboard
//https://github.com/hzeller/rpi-rgb-led-matrix
//https://learn.adafruit.com/raspberry-pi-rgb-led-matrix-webapp?view=all
//http://www.instructables.com/id/Disable-the-Built-in-Sound-Card-of-Raspberry-Pi/

**Comment by ajbowler** [comment]
Thanks, appreciate the writeup. However I'm trying to keep the scope of the README down to the scoreboard project itself. I reference the rgbmatrix project's README where necessary to install their code but apart from that I try to keep things simple.

Setting up a Raspberry Pi as well as embedding some of the rgbmatrix instructions aren't within the scope here.
